services:
  - type: web
    name: fptu-connect
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python generate_graph.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      PYTHON_VERSION: "3.11"
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1